# Generated by Django 2.1.3 on 2018-12-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30)),
                ('precio', models.IntegerField()),
                ('negociable', models.BooleanField()),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('ubicacionDepartamento', models.CharField(max_length=30)),
                ('ubicacionCiudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('kilometraje', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('nPuertas', models.IntegerField()),
                ('aireAcondicionado', models.BooleanField()),
                ('vidriosElectricos', models.BooleanField()),
                ('tipoDireccion', models.CharField(max_length=20)),
                ('tipoTransmision', models.CharField(max_length=20)),
                ('airbag', models.BooleanField()),
                ('nAsientos', models.BooleanField()),
                ('alarma', models.BooleanField()),
                ('sunroof', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anuncio.Vehiculo'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
