# Generated by Django 2.1.3 on 2018-12-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='vendedor',
            new_name='user',
        ),
    ]
