# Generated by Django 2.1.3 on 2018-12-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_auto_20181207_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
